Create Vue-Fluid-DnD.md
CuCodersCommunity/cucoderscommunity.github.io pull request #129
Opened 2024-04-28 16:42 UTC by carlosjorger

Add Vue-Fluid-DnD library to the app catalog

2024-05-04 22:02 UTC, manuelernestog requested changes

2024-05-04 22:02 UTC, manuelernestog commented on src/content/apps/carlosjorger/Vue-Fluid-DnD.md
> +Aquí va la descripción general de tu app en formato MarkDown.
@carlosjorger  Aqui va la descripción como tal de la lib, si quieres la pudes poner con formato MD o eliminar la línea.

2024-05-07 00:54 UTC, carlosjorger commented on src/content/apps/carlosjorger/Vue-Fluid-DnD.md
> +Aquí va la descripción general de tu app en formato MarkDown.
ok ya removí el comentario

2024-05-08 19:18 UTC, manuelernestog approved these changes

2024-05-08 19:19 UTC, merged